import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Sheard/Header";
import Footer from "@/components/Sheard/Footer";
import AuthProvider from "@/Providers/AuthProvider";
import toast, { Toaster } from 'react-hot-toast';

const notify = () => toast('Here is your toast.');

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <body className={inter.className} suppressHydrationWarning={true}>
        <AuthProvider>
        
          <Header></Header>
          <div className="container mx-auto my-4">
            {children}
          </div>
          <Footer></Footer>
          <Toaster/>
        </AuthProvider>
        
      </body>
    </html>
  );
}
